---
- name: "Retrieve all resources for resource group."
  azure_rm_resourcegroup_info:
    name: "{{ resource_group.name }}"
    list_resources: true
  register: rg_resources
  when: ansible_verbosity > 0

- name: "List resources which will be deleted along with group."
  debug:
    msg: "{{ rg_resources }}"
  when: ansible_verbosity > 0

- name: "Delete resource group."
  azure_rm_resourcegroup:
    name: "{{ resource_group.name }}"
    state: "absent"
    force_delete_nonempty: true
